# Configuration for kicking off the deployment (files and directories)
global:
  spec:
    kubernetes:
      serviceAccount: sre-sa
    tools:
        helm:
          version: "v3.0.2"
    env:
      - name: IMAGE_TAG
        value: "latest"
environments:
  - name: dev
    instances:
      - name: devcluster
        spec:
          kubernetes:
            cluster: devcluster.my-domain.com
          env:
          - name: NAMESPACE
            value: default
  - name: test
    instances:
      - name: aqua
        spec:
          kubernetes:
            cluster: aqua.readytalk.io
          env:
          - name: NAMESPACE
            value: default
